# Generated by Django 5.1 on 2024-09-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InitialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.DateTimeField()),
                ('time_of_fire_out', models.DateTimeField()),
                ('occupancy_type', models.CharField(max_length=255)),
                ('name_of_owner', models.CharField(max_length=255)),
                ('alarm_status', models.CharField(max_length=255)),
                ('no_of_respondents', models.IntegerField()),
                ('estimated_damage', models.CharField(max_length=255)),
                ('no_of_establishments', models.IntegerField()),
                ('no_of_casualties', models.IntegerField()),
                ('no_of_injured', models.IntegerField()),
                ('proof', models.ImageField(blank=True, null=True, upload_to='proofs/')),
            ],
        ),
    ]
