# Generated by Django 5.1 on 2024-09-27 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FireDetection', '0003_customuser_name_customuser_role_customuser_verified'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
