# Generated by Django 5.1 on 2024-09-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FireDetection', '0004_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialreport',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
