# Generated by Django 5.1 on 2024-10-19 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FireDetection', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialreport',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
