# Generated by Django 5.1 on 2024-11-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FireDetection', '0005_remove_initialreport_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Radio Operator', 'Radio Operator'), ('Responder', 'Responder')], default='Responder', max_length=30),
        ),
    ]
