# Generated by Django 5.1 on 2024-11-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FireDetection', '0007_customuser_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialreport',
            name='fir_number',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True),
        ),
    ]
