# Generated by Django 5.1.3 on 2024-11-25 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FireDetection', '0008_initialreport_fir_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialreport',
            name='proof',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tempreports',
            name='proof',
            field=models.URLField(max_length=255),
        ),
    ]
