# Generated by Django 5.1 on 2024-12-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FireDetection', '0009_alter_initialreport_proof_alter_tempreports_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempreports',
            name='status',
            field=models.CharField(choices=[('Reported', 'Reported'), ('Dismissed', 'Dismissed')], max_length=20, null=True),
        ),
    ]
