# Generated by Django 5.1 on 2025-01-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FireDetection', '0010_alter_tempreports_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialreport',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
