# Generated by Django 5.1.4 on 2024-12-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FireDetection', '0010_alter_tempreports_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempreports',
            name='is_transferred',
            field=models.BooleanField(default=False),
        ),
    ]
